version: "2"
services:
  hugo:
    build: ./hugo
    ports:
      - "1313:1313"
    volumes:
      - "./hugo/site:/usr/share/blog"
  webpack:
    build: ./webpack
    volumes:
      - "./hugo/site/static:/app/dist"
      - "./webpack/src:/app/src"
      - "./webpack/config:/app/config"
    command: "./node_modules/.bin/webpack --config app/config/webpack.config.js"

networks:
  default:
    external:
      name: itprotv_bridge
